In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>")) #makes the display bars longer and spread out 100% across the screen width

In [2]:
from vivarium import Artifact
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from db_queries import get_ids, get_outputs
import scipy.stats

In [3]:
#find file paths
%cd /share/costeffectiveness/results/vivarium_gates_bep/fall_2020/5_a/india/2020_10_14_14_22_44/count_data
%ls

!whoami
!date

/ihme/costeffectiveness/results/vivarium_gates_bep/fall_2020/5_a/india/2020_10_14_14_22_44/count_data
birth_weight.csv    deaths.csv           population.csv         ylds.csv
birth_weight.hdf    deaths.hdf           population.hdf         ylds.hdf
cgf_categories.csv  gestational_age.csv  state_person_time.csv  ylls.csv
cgf_categories.hdf  gestational_age.hdf  state_person_time.hdf  ylls.hdf
cgf_z_scores.csv    person_time.csv      transition_count.csv
cgf_z_scores.hdf    person_time.hdf      transition_count.hdf
nicoly
Thu Oct 15 22:24:11 PDT 2020

In [4]:
#find file paths
%cd /share/costeffectiveness/results/vivarium_gates_bep/fall_2020/5_b/india/2020_10_14_14_43_07/count_data
%ls

!whoami
!date

/ihme/costeffectiveness/results/vivarium_gates_bep/fall_2020/5_b/india/2020_10_14_14_43_07/count_data
birth_weight.csv    deaths.csv           population.csv         ylds.csv
birth_weight.hdf    deaths.hdf           population.hdf         ylds.hdf
cgf_categories.csv  gestational_age.csv  state_person_time.csv  ylls.csv
cgf_categories.hdf  gestational_age.hdf  state_person_time.hdf  ylls.hdf
cgf_z_scores.csv    person_time.csv      transition_count.csv
cgf_z_scores.hdf    person_time.hdf      transition_count.hdf
nicoly
Thu Oct 15 22:24:11 PDT 2020

In [5]:
#scenarios in each of the runs

#run1 (baseline, mmn, bep_hd_universal_i & targeted_i)
#run2 (bep_ce_universal & targeted)
#run3 (bep_ce_universal & targeted)
#run4 (baseline, mmn, bep_hd_universal_iii & targeted_iii)

#summer model
#scenarios in each of the runs

#run1 (baseline, mmn, bep_hd_universal_i & targeted_i)
#run2 (bep_ce_universal & targeted)
#run3 (bep_ce_universal & targeted)
#run4 (baseline, mmn, bep_hd_universal_iii & targeted_iii)

output_dirs5a = ['/share/costeffectiveness/results/vivarium_gates_bep/fall_2020/5_a/india/2020_10_14_14_22_44/count_data/']

output_dirs5b = ['/share/costeffectiveness/results/vivarium_gates_bep/fall_2020/5_b/india/2020_10_14_14_43_07/count_data/']

#location labels
locations = ['India','Pakistan','Mali','Tanzania']

#use in sort_values to make custum sort list. I sorted by region. 
sorter = ['India','mali','Mali','Tanzania']
sorterIndex = dict(zip(sorter,range(len(sorter))))

#feb model
output_dirs = ['/share/costeffectiveness/results/vivarium_gates_bep/malnutrition/india/2020_02_05_03_02_13/count_space/',
              '/share/costeffectiveness/results/vivarium_gates_bep/malnutrition/mali/2020_02_05_03_02_02/count_space/',
              '/share/costeffectiveness/results/vivarium_gates_bep/malnutrition/tanzania/2020_02_05_03_07_37/count_space/']



#location labels
locations = ['India','Pakistan','Mali','Tanzania']

#use in sort_values to make custum sort list. I sorted by region. 
sorter = ['India','Pakistan','Mali','Tanzania']
sorterIndex = dict(zip(sorter,range(len(sorter))))

## testing

In [6]:
cgf_india = pd.read_hdf('/share/costeffectiveness/results/vivarium_gates_bep/fall_2020/5_a/india/2020_10_14_14_22_44/count_data/cgf_z_scores.hdf').reset_index()
print(len(cgf_india))
cgf_india.head()

12800

,index,risk,treatment_group,mother_status,measure,input_draw,scenario,value,timepoint
0,0,stunting,bep,malnourished,mean,3,baseline,0.000000,twenty_nine_days
1,1,stunting,bep,malnourished,mean,3,baseline,0.000000,three_six_six_days
2,2,stunting,bep,malnourished,mean,3,bep_ce_scale_up,9.553532,twenty_nine_days
3,3,stunting,bep,malnourished,mean,3,bep_ce_scale_up,8.884770,three_six_six_days
4,4,stunting,bep,malnourished,mean,3,bep_ce_targeted_scale_up,9.553532,twenty_nine_days

In [7]:
cgf_india['treatment_group'].value_counts()

mmn     3200
ifa     3200
bep     3200
none    3200
Name: treatment_group, dtype: int64

In [8]:
deaths_india = pd.read_hdf('/share/costeffectiveness/results/vivarium_gates_bep/fall_2020/5_a/india/2020_10_14_14_22_44/count_data/deaths.hdf')
deaths_india.head()

,age_group,cause,treatment_group,mother_status,measure,input_draw,scenario,value
0,1_to_4,diarrheal_diseases,bep,malnourished,death,3,baseline,0.0
1,1_to_4,diarrheal_diseases,bep,malnourished,death,3,bep_ce_scale_up,1.0
2,1_to_4,diarrheal_diseases,bep,malnourished,death,3,bep_ce_targeted_scale_up,1.0
3,1_to_4,diarrheal_diseases,bep,malnourished,death,3,mmn_scale_up,0.0
4,1_to_4,diarrheal_diseases,bep,malnourished,death,21,baseline,0.0

In [9]:
deaths_india['cause'].value_counts()

diarrheal_diseases              8000
measles                         8000
protein_energy_malnutrition     8000
lower_respiratory_infections    8000
other_causes                    8000
Name: cause, dtype: int64

In [10]:
died_india = deaths_india.groupby(['input_draw', 'scenario','mother_status', 'treatment_group']).sum().reset_index()
died_india = died_india.rename(columns={'value':'deaths'})
died_india.head()

   input_draw  scenario mother_status treatment_group  deaths
0           3  baseline  malnourished             bep     0.0
1           3  baseline  malnourished             ifa   243.0
2           3  baseline  malnourished             mmn     0.0
3           3  baseline  malnourished            none   466.0
4           3  baseline        normal             bep     0.0

# CGF z-score shift check

# ------------------------------------------------------------------------------------

## RUN 5a BASELINE, MMN, BEP_CE_scale_up, BEP_TARGETED_scale_up

In [11]:
#RUN 5a (bep_ce_universal & targeted)

master_cgf_5a = pd.DataFrame()

for i in list(range(len(output_dirs5a))):
    #cgf
    cgf_5a = pd.read_hdf(output_dirs5a[i] + 'cgf_z_scores.hdf').reset_index().sort_values(by=['input_draw','risk','measure','scenario','treatment_group','mother_status'])
    cgf_5a = cgf_5a.rename(columns={'value':'zscore'})
    cgf_5a['Z_SCORE'] = cgf_5a['zscore'] - 10
    
    #population
    pop = pd.read_hdf(output_dirs5a[i] + 'population.hdf').reset_index()
    pop = pop.where(pop['measure'] == 'total_population').dropna().rename(columns={'value':'start_population'}).drop(columns=['index','measure'])
    
    died = pd.read_hdf(output_dirs5a[i] + 'deaths.hdf')
    died = died.groupby(['input_draw', 'scenario','mother_status','treatment_group']).sum().rename(columns={'value':'deaths'}).reset_index()
    
    pop = pop.merge(died, right_on=['scenario','treatment_group','mother_status','input_draw'], left_on=['scenario','treatment_group','mother_status','input_draw'])
    
    data = pd.merge(cgf_5a, pop, left_on=['input_draw','scenario','treatment_group','mother_status'], right_on=['input_draw','scenario','treatment_group','mother_status'], how='outer')
    
    data = data.groupby(['risk','measure','scenario','treatment_group','mother_status','timepoint']).mean().drop(columns=['input_draw','index']).reset_index() #average over input draws
    
    data['alive'] = data['start_population'] - data['deaths']
    data['alive_x_cgf'] = data['Z_SCORE'] * data['alive'] #cannot use this as weight because the population is the population supplemented (or at birth) whereas the z-score is among alive population at 2 years
    data['location'] = locations[i]
    master_cgf_5a = master_cgf_5a.append(data)
    
master_cgf_5a.head()

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
0,stunting,mean,baseline,bep,malnourished,three_six_six_days,0.00000,-10.00000,0.00,0.00,0.0,-0.000000,India
1,stunting,mean,baseline,bep,malnourished,twenty_nine_days,0.00000,-10.00000,0.00,0.00,0.0,-0.000000,India
2,stunting,mean,baseline,bep,normal,three_six_six_days,0.00000,-10.00000,0.00,0.00,0.0,-0.000000,India
3,stunting,mean,baseline,bep,normal,twenty_nine_days,0.00000,-10.00000,0.00,0.00,0.0,-0.000000,India
4,stunting,mean,baseline,ifa,malnourished,three_six_six_days,8.86222,-1.13778,5770.46,225.86,5544.6,-6308.535873,India


# -----------------------------------------------
## STUNTING -baseline

#### 1) 29 days

In [34]:
# STUNTING BASELINE 29days

# ARTIFACT = -0.887103 (india)

stunting_5a_baseline29 = master_cgf_5a[master_cgf_5a['risk'].isin(['stunting']) & \
                                    master_cgf_5a['timepoint'].isin(['twenty_nine_days']) & \
                                    master_cgf_5a['scenario'].isin(['baseline']) & \
                                    master_cgf_5a['treatment_group'].isin(['ifa','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -0.887103 29 days (india)')
stunting_5a_baseline29

artifact = -0.887103 29 days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
5,stunting,mean,baseline,ifa,malnourished,twenty_nine_days,9.590450,-0.409550,5770.46,225.86,5544.60,-2270.793292,India
7,stunting,mean,baseline,ifa,normal,twenty_nine_days,9.589119,-0.410881,28262.46,960.80,27301.66,-11217.740098,India
13,stunting,mean,baseline,none,malnourished,twenty_nine_days,9.596468,-0.403532,11166.04,479.46,10686.58,-4312.371927,India
15,stunting,mean,baseline,none,normal,twenty_nine_days,9.587644,-0.412356,54801.04,1927.68,52873.36,-21802.643352,India

#### 2) 366 days

In [33]:
# STUNTING BASELINE 366days

# ARTIFACT = -1.587298 (india)

stunting_5a_baseline366 = master_cgf_5a[master_cgf_5a['risk'].isin(['stunting']) & \
                                    master_cgf_5a['timepoint'].isin(['three_six_six_days']) & \
                                    master_cgf_5a['scenario'].isin(['baseline']) & \
                                    master_cgf_5a['treatment_group'].isin(['ifa','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -1.587298 366 days(india)')
stunting_5a_baseline366

artifact = -1.587298 366 days(india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
4,stunting,mean,baseline,ifa,malnourished,three_six_six_days,8.862220,-1.137780,5770.46,225.86,5544.60,-6308.535873,India
6,stunting,mean,baseline,ifa,normal,three_six_six_days,8.861468,-1.138532,28262.46,960.80,27301.66,-31083.823458,India
12,stunting,mean,baseline,none,malnourished,three_six_six_days,8.867354,-1.132646,11166.04,479.46,10686.58,-12104.107677,India
14,stunting,mean,baseline,none,normal,three_six_six_days,8.860018,-1.139982,54801.04,1927.68,52873.36,-60274.662058,India

## STUNTING -MMN

#### 3) 29 days

In [22]:
## STUNTING 29days

stunting_5a_mmn29 = master_cgf_5a[master_cgf_5a['risk'].isin(['stunting']) & \
                                    master_cgf_5a['timepoint'].isin(['twenty_nine_days']) & \
                                    master_cgf_5a['scenario'].isin(['mmn_scale_up']) & \
                                    master_cgf_5a['treatment_group'].isin(['mmn','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -0.887103 29days (india)')
stunting_5a_mmn29

artifact = -0.887103 (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
57,stunting,mean,mmn_scale_up,mmn,malnourished,twenty_nine_days,9.587445,-0.412555,13444.32,500.78,12943.54,-5339.922957,India
59,stunting,mean,mmn_scale_up,mmn,normal,twenty_nine_days,9.586661,-0.413339,65971.26,2186.44,63784.82,-26364.723750,India
61,stunting,mean,mmn_scale_up,none,malnourished,twenty_nine_days,9.602632,-0.397368,3492.18,149.86,3342.32,-1328.131399,India
63,stunting,mean,mmn_scale_up,none,normal,twenty_nine_days,9.586584,-0.413416,17092.24,600.96,16491.28,-6817.755247,India

#### 4) 366 days

In [23]:
# STUNTING 366days

stunting_5a_mmn366 = master_cgf_5a[master_cgf_5a['risk'].isin(['stunting']) & \
                                    master_cgf_5a['timepoint'].isin(['three_six_six_days']) & \
                                    master_cgf_5a['scenario'].isin(['mmn_scale_up']) & \
                                    master_cgf_5a['treatment_group'].isin(['mmn','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -1.587298 366days (india)')
stunting_5a_mmn366

artifact = -1.587298 (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
56,stunting,mean,mmn_scale_up,mmn,malnourished,three_six_six_days,8.859528,-1.140472,13444.32,500.78,12943.54,-14761.739035,India
58,stunting,mean,mmn_scale_up,mmn,normal,three_six_six_days,8.859192,-1.140808,65971.26,2186.44,63784.82,-72766.201158,India
60,stunting,mean,mmn_scale_up,none,malnourished,three_six_six_days,8.872515,-1.127485,3492.18,149.86,3342.32,-3768.414280,India
62,stunting,mean,mmn_scale_up,none,normal,three_six_six_days,8.859213,-1.140787,17092.24,600.96,16491.28,-18813.045787,India

## STUNTING -BEP CURRENT EVIDENCE (CE) UNIVERSAL

#### 5) 29 days

In [35]:
## STUNTING 29days

stunting_5a_bep_ce_universal_29 = master_cgf_5a[master_cgf_5a['risk'].isin(['stunting']) & \
                                    master_cgf_5a['timepoint'].isin(['twenty_nine_days']) & \
                                    master_cgf_5a['scenario'].isin(['bep_ce_scale_up']) & \
                                    master_cgf_5a['treatment_group'].isin(['bep','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -0.887103 29days (india)')
stunting_5a_bep_ce_universal_29

artifact = -0.887103 29days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
17,stunting,mean,bep_ce_scale_up,bep,malnourished,twenty_nine_days,9.584384,-0.415616,13444.32,469.30,12975.02,-5392.621706,India
19,stunting,mean,bep_ce_scale_up,bep,normal,twenty_nine_days,9.586246,-0.413754,65971.26,2164.22,63807.04,-26400.395275,India
29,stunting,mean,bep_ce_scale_up,none,malnourished,twenty_nine_days,9.602632,-0.397368,3492.18,149.86,3342.32,-1328.131399,India
31,stunting,mean,bep_ce_scale_up,none,normal,twenty_nine_days,9.586584,-0.413416,17092.24,600.96,16491.28,-6817.755247,India

#### 6) 366 days

In [36]:
## STUNTING 366days

stunting_5a_bep_ce_universal_366 = master_cgf_5a[master_cgf_5a['risk'].isin(['stunting']) & \
                                    master_cgf_5a['timepoint'].isin(['three_six_six_days']) & \
                                    master_cgf_5a['scenario'].isin(['bep_ce_scale_up']) & \
                                    master_cgf_5a['treatment_group'].isin(['bep','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -1.587298 366days (india)')
stunting_5a_bep_ce_universal_366

artifact = -1.587298 366days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
16,stunting,mean,bep_ce_scale_up,bep,malnourished,three_six_six_days,8.856829,-1.143171,13444.32,469.30,12975.02,-14832.667928,India
18,stunting,mean,bep_ce_scale_up,bep,normal,three_six_six_days,8.858827,-1.141173,65971.26,2164.22,63807.04,-72814.865058,India
28,stunting,mean,bep_ce_scale_up,none,malnourished,three_six_six_days,8.872515,-1.127485,3492.18,149.86,3342.32,-3768.414280,India
30,stunting,mean,bep_ce_scale_up,none,normal,three_six_six_days,8.859213,-1.140787,17092.24,600.96,16491.28,-18813.045787,India

## STUNTING -BEP CURRENT EVIDENCE (CE) TARGETED

#### 7) 29 days

In [37]:
## STUNTING 29days

stunting_5a_bep_ce_targeted_29 = master_cgf_5a[master_cgf_5a['risk'].isin(['stunting']) & \
                                    master_cgf_5a['timepoint'].isin(['twenty_nine_days']) & \
                                    master_cgf_5a['scenario'].isin(['bep_ce_targeted_scale_up']) & \
                                    master_cgf_5a['treatment_group'].isin(['bep','mmn','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -0.887103 29days (india)')
stunting_5a_bep_ce_targeted_29

artifact = -0.887103 29days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
33,stunting,mean,bep_ce_targeted_scale_up,bep,malnourished,twenty_nine_days,9.584384,-0.415616,13444.32,469.30,12975.02,-5392.621706,India
35,stunting,mean,bep_ce_targeted_scale_up,bep,normal,twenty_nine_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
41,stunting,mean,bep_ce_targeted_scale_up,mmn,malnourished,twenty_nine_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
43,stunting,mean,bep_ce_targeted_scale_up,mmn,normal,twenty_nine_days,9.586661,-0.413339,65971.26,2186.44,63784.82,-26364.723750,India
45,stunting,mean,bep_ce_targeted_scale_up,none,malnourished,twenty_nine_days,9.602632,-0.397368,3492.18,149.86,3342.32,-1328.131399,India
47,stunting,mean,bep_ce_targeted_scale_up,none,normal,twenty_nine_days,9.586584,-0.413416,17092.24,600.96,16491.28,-6817.755247,India

#### 8) 366 days

In [38]:
## STUNTING 366days

stunting_5a_bep_ce_targeted_366 = master_cgf_5a[master_cgf_5a['risk'].isin(['stunting']) & \
                                    master_cgf_5a['timepoint'].isin(['three_six_six_days']) & \
                                    master_cgf_5a['scenario'].isin(['bep_ce_targeted_scale_up']) & \
                                    master_cgf_5a['treatment_group'].isin(['bep','mmn','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -1.587298 366days (india)')
stunting_5a_bep_ce_targeted_366

artifact = -1.587298 366days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
32,stunting,mean,bep_ce_targeted_scale_up,bep,malnourished,three_six_six_days,8.856829,-1.143171,13444.32,469.30,12975.02,-14832.667928,India
34,stunting,mean,bep_ce_targeted_scale_up,bep,normal,three_six_six_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
40,stunting,mean,bep_ce_targeted_scale_up,mmn,malnourished,three_six_six_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
42,stunting,mean,bep_ce_targeted_scale_up,mmn,normal,three_six_six_days,8.859192,-1.140808,65971.26,2186.44,63784.82,-72766.201158,India
44,stunting,mean,bep_ce_targeted_scale_up,none,malnourished,three_six_six_days,8.872515,-1.127485,3492.18,149.86,3342.32,-3768.414280,India
46,stunting,mean,bep_ce_targeted_scale_up,none,normal,three_six_six_days,8.859213,-1.140787,17092.24,600.96,16491.28,-18813.045787,India

# -------------------------------------------

# WASTING

## WASTING- baseline

#### 1) 29 days

In [43]:
# wasting BASELINE 29days


wasting_5a_baseline29 = master_cgf_5a[master_cgf_5a['risk'].isin(['wasting']) & \
                                    master_cgf_5a['timepoint'].isin(['twenty_nine_days']) & \
                                    master_cgf_5a['scenario'].isin(['baseline']) & \
                                    master_cgf_5a['treatment_group'].isin(['ifa','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -0.451174 wasting 29 days (india)')
wasting_5a_baseline29

artifact = -0.451174 wasting 29 days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
133,wasting,mean,baseline,ifa,malnourished,twenty_nine_days,9.710384,-0.289616,5770.46,225.86,5544.60,-1605.807296,India
135,wasting,mean,baseline,ifa,normal,twenty_nine_days,9.706311,-0.293689,28262.46,960.80,27301.66,-8018.199740,India
141,wasting,mean,baseline,none,malnourished,twenty_nine_days,9.711895,-0.288105,11166.04,479.46,10686.58,-3078.855701,India
143,wasting,mean,baseline,none,normal,twenty_nine_days,9.706538,-0.293462,54801.04,1927.68,52873.36,-15516.300852,India

#### 2) 366 days

In [44]:
# wasting BASELINE 366days

wasting_5a_baseline366 = master_cgf_5a[master_cgf_5a['risk'].isin(['wasting']) & \
                                    master_cgf_5a['timepoint'].isin(['three_six_six_days']) & \
                                    master_cgf_5a['scenario'].isin(['baseline']) & \
                                    master_cgf_5a['treatment_group'].isin(['ifa','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -0.536096 wasting 366 days(india)')
wasting_5a_baseline366

artifact = -0.536096 wasting 366 days(india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
132,wasting,mean,baseline,ifa,malnourished,three_six_six_days,9.600681,-0.399319,5770.46,225.86,5544.60,-2214.062143,India
134,wasting,mean,baseline,ifa,normal,three_six_six_days,9.596696,-0.403304,28262.46,960.80,27301.66,-11010.874415,India
140,wasting,mean,baseline,none,malnourished,three_six_six_days,9.601587,-0.398413,11166.04,479.46,10686.58,-4257.676117,India
142,wasting,mean,baseline,none,normal,three_six_six_days,9.596925,-0.403075,54801.04,1927.68,52873.36,-21311.934135,India

## WASTING -MMN

#### 3) 29 days

In [45]:
## wasting 29days

wasting_5a_mmn29 = master_cgf_5a[master_cgf_5a['risk'].isin(['wasting']) & \
                                    master_cgf_5a['timepoint'].isin(['twenty_nine_days']) & \
                                    master_cgf_5a['scenario'].isin(['mmn_scale_up']) & \
                                    master_cgf_5a['treatment_group'].isin(['mmn','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -0.451174 wasting 29 days (india)')
wasting_5a_mmn29

artifact = -0.451174 wasting 29 days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
185,wasting,mean,mmn_scale_up,mmn,malnourished,twenty_nine_days,9.707425,-0.292575,13444.32,500.78,12943.54,-3786.954068,India
187,wasting,mean,mmn_scale_up,mmn,normal,twenty_nine_days,9.704692,-0.295308,65971.26,2186.44,63784.82,-18836.177767,India
189,wasting,mean,mmn_scale_up,none,malnourished,twenty_nine_days,9.713408,-0.286592,3492.18,149.86,3342.32,-957.881169,India
191,wasting,mean,mmn_scale_up,none,normal,twenty_nine_days,9.708614,-0.291386,17092.24,600.96,16491.28,-4805.320942,India

#### 4) 366 days

In [46]:
# WASTING 366days

wasting_5a_mmn366 = master_cgf_5a[master_cgf_5a['risk'].isin(['wasting']) & \
                                    master_cgf_5a['timepoint'].isin(['three_six_six_days']) & \
                                    master_cgf_5a['scenario'].isin(['mmn_scale_up']) & \
                                    master_cgf_5a['treatment_group'].isin(['mmn','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -0.536096 wasting 366 days(india)')
wasting_5a_mmn366

artifact = -0.536096 wasting 366 days(india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
184,wasting,mean,mmn_scale_up,mmn,malnourished,three_six_six_days,9.597614,-0.402386,13444.32,500.78,12943.54,-5208.299764,India
186,wasting,mean,mmn_scale_up,mmn,normal,three_six_six_days,9.595265,-0.404735,65971.26,2186.44,63784.82,-25815.970119,India
188,wasting,mean,mmn_scale_up,none,malnourished,three_six_six_days,9.603490,-0.396510,3492.18,149.86,3342.32,-1325.264242,India
190,wasting,mean,mmn_scale_up,none,normal,three_six_six_days,9.598711,-0.401289,17092.24,600.96,16491.28,-6617.772931,India

## WASTING -BEP CURRENT EVIDENCE (CE) UNIVERSAL

#### 5) 29 days

In [47]:
## WASTING 29days

wasting_5a_bep_ce_universal_29 = master_cgf_5a[master_cgf_5a['risk'].isin(['wasting']) & \
                                    master_cgf_5a['timepoint'].isin(['twenty_nine_days']) & \
                                    master_cgf_5a['scenario'].isin(['bep_ce_scale_up']) & \
                                    master_cgf_5a['treatment_group'].isin(['bep','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -0.451174 wasting 29 days (india)')
wasting_5a_bep_ce_universal_29

artifact = -0.451174 wasting 29 days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
145,wasting,mean,bep_ce_scale_up,bep,malnourished,twenty_nine_days,9.705556,-0.294444,13444.32,469.30,12975.02,-3820.416822,India
147,wasting,mean,bep_ce_scale_up,bep,normal,twenty_nine_days,9.704412,-0.295588,65971.26,2164.22,63807.04,-18860.616681,India
157,wasting,mean,bep_ce_scale_up,none,malnourished,twenty_nine_days,9.713408,-0.286592,3492.18,149.86,3342.32,-957.881169,India
159,wasting,mean,bep_ce_scale_up,none,normal,twenty_nine_days,9.708614,-0.291386,17092.24,600.96,16491.28,-4805.320942,India

#### 6) 366 days

In [48]:
## WASTING 366days

wasting_5a_bep_ce_universal_366 = master_cgf_5a[master_cgf_5a['risk'].isin(['wasting']) & \
                                    master_cgf_5a['timepoint'].isin(['three_six_six_days']) & \
                                    master_cgf_5a['scenario'].isin(['bep_ce_scale_up']) & \
                                    master_cgf_5a['treatment_group'].isin(['bep','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -0.536096 wasting 366 days(india)')
wasting_5a_bep_ce_universal_366

artifact = -0.536096 wasting 366 days(india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
144,wasting,mean,bep_ce_scale_up,bep,malnourished,three_six_six_days,9.595922,-0.404078,13444.32,469.30,12975.02,-5242.926119,India
146,wasting,mean,bep_ce_scale_up,bep,normal,three_six_six_days,9.595019,-0.404981,65971.26,2164.22,63807.04,-25840.625394,India
156,wasting,mean,bep_ce_scale_up,none,malnourished,three_six_six_days,9.603490,-0.396510,3492.18,149.86,3342.32,-1325.264242,India
158,wasting,mean,bep_ce_scale_up,none,normal,three_six_six_days,9.598711,-0.401289,17092.24,600.96,16491.28,-6617.772931,India

## WASTING -BEP CURRENT EVIDENCE (CE) TARGETED

#### 7) 29 days

In [50]:
## WASTING 29days

wasting_5a_bep_ce_targeted_29 = master_cgf_5a[master_cgf_5a['risk'].isin(['wasting']) & \
                                    master_cgf_5a['timepoint'].isin(['twenty_nine_days']) & \
                                    master_cgf_5a['scenario'].isin(['bep_ce_targeted_scale_up']) & \
                                    master_cgf_5a['treatment_group'].isin(['bep','mmn','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -0.451174 wasting 29 days (india)')
wasting_5a_bep_ce_targeted_29

artifact = -0.451174 wasting 29 days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
161,wasting,mean,bep_ce_targeted_scale_up,bep,malnourished,twenty_nine_days,9.705556,-0.294444,13444.32,469.30,12975.02,-3820.416822,India
163,wasting,mean,bep_ce_targeted_scale_up,bep,normal,twenty_nine_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
169,wasting,mean,bep_ce_targeted_scale_up,mmn,malnourished,twenty_nine_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
171,wasting,mean,bep_ce_targeted_scale_up,mmn,normal,twenty_nine_days,9.704692,-0.295308,65971.26,2186.44,63784.82,-18836.177767,India
173,wasting,mean,bep_ce_targeted_scale_up,none,malnourished,twenty_nine_days,9.713408,-0.286592,3492.18,149.86,3342.32,-957.881169,India
175,wasting,mean,bep_ce_targeted_scale_up,none,normal,twenty_nine_days,9.708614,-0.291386,17092.24,600.96,16491.28,-4805.320942,India

#### 8) 366 days

In [49]:
## wasting 366days

wasting_5a_bep_ce_targeted_366 = master_cgf_5a[master_cgf_5a['risk'].isin(['wasting']) & \
                                    master_cgf_5a['timepoint'].isin(['three_six_six_days']) & \
                                    master_cgf_5a['scenario'].isin(['bep_ce_targeted_scale_up']) & \
                                    master_cgf_5a['treatment_group'].isin(['bep','mmn','none']) & \
                                    master_cgf_5a['location'].isin(['India']) & \
                                    master_cgf_5a['measure'].isin(['mean'])]
print('artifact = -0.536096 wasting 366 days(india)')
wasting_5a_bep_ce_targeted_366

artifact = -0.536096 wasting 366 days(india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
160,wasting,mean,bep_ce_targeted_scale_up,bep,malnourished,three_six_six_days,9.595922,-0.404078,13444.32,469.30,12975.02,-5242.926119,India
162,wasting,mean,bep_ce_targeted_scale_up,bep,normal,three_six_six_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
168,wasting,mean,bep_ce_targeted_scale_up,mmn,malnourished,three_six_six_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
170,wasting,mean,bep_ce_targeted_scale_up,mmn,normal,three_six_six_days,9.595265,-0.404735,65971.26,2186.44,63784.82,-25815.970119,India
172,wasting,mean,bep_ce_targeted_scale_up,none,malnourished,three_six_six_days,9.603490,-0.396510,3492.18,149.86,3342.32,-1325.264242,India
174,wasting,mean,bep_ce_targeted_scale_up,none,normal,three_six_six_days,9.598711,-0.401289,17092.24,600.96,16491.28,-6617.772931,India

# ------------------------------------------------------------------------------------

## RUN 5b BEP_HD_scale_up, BEP_HD_targeted_scale_up

In [55]:
#RUN 5b (bep_ce_universal & targeted)

master_cgf_5b = pd.DataFrame()

for i in list(range(len(output_dirs5b))):
    #cgf
    cgf_5b = pd.read_hdf(output_dirs5b[i] + 'cgf_z_scores.hdf').reset_index().sort_values(by=['input_draw','risk','measure','scenario','treatment_group','mother_status'])
    cgf_5b = cgf_5b.rename(columns={'value':'zscore'})
    cgf_5b['Z_SCORE'] = cgf_5b['zscore'] - 10
    
    #population
    pop = pd.read_hdf(output_dirs5b[i] + 'population.hdf').reset_index()
    pop = pop.where(pop['measure'] == 'total_population').dropna().rename(columns={'value':'start_population'}).drop(columns=['index','measure'])
    
    died = pd.read_hdf(output_dirs5b[i] + 'deaths.hdf')
    died = died.groupby(['input_draw', 'scenario','mother_status','treatment_group']).sum().rename(columns={'value':'deaths'}).reset_index()
    
    pop = pop.merge(died, right_on=['scenario','treatment_group','mother_status','input_draw'], left_on=['scenario','treatment_group','mother_status','input_draw'])
    
    data = pd.merge(cgf_5b, pop, left_on=['input_draw','scenario','treatment_group','mother_status'], right_on=['input_draw','scenario','treatment_group','mother_status'], how='outer')
    
    data = data.groupby(['risk','measure','scenario','treatment_group','mother_status','timepoint']).mean().drop(columns=['input_draw','index']).reset_index() #average over input draws
    
    data['alive'] = data['start_population'] - data['deaths']
    data['alive_x_cgf'] = data['Z_SCORE'] * data['alive'] #cannot use this as weight because the population is the population supplemented (or at birth) whereas the z-score is among alive population at 2 years
    data['location'] = locations[i]
    master_cgf_5b = master_cgf_5b.append(data)
    
master_cgf_5b.head()

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
0,stunting,mean,bep_hd_scale_up,bep,malnourished,three_six_six_days,8.755263,-1.244737,13444.32,449.88,12994.44,-16174.661623,India
1,stunting,mean,bep_hd_scale_up,bep,malnourished,twenty_nine_days,9.407598,-0.592402,13444.32,449.88,12994.44,-7697.927249,India
2,stunting,mean,bep_hd_scale_up,bep,normal,three_six_six_days,8.756869,-1.243131,65971.26,2045.44,63925.82,-79468.188732,India
3,stunting,mean,bep_hd_scale_up,bep,normal,twenty_nine_days,9.409123,-0.590877,65971.26,2045.44,63925.82,-37772.281310,India
4,stunting,mean,bep_hd_scale_up,ifa,malnourished,three_six_six_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India

## STUNTING -BEP HOPES N DREAMS (HD) UNIVERSAL

### 1) 29 days

In [59]:
## STUNTING 29days

stunting_5b_bep_hd_universal_29 = master_cgf_5b[master_cgf_5b['risk'].isin(['stunting']) & \
                                    master_cgf_5b['timepoint'].isin(['twenty_nine_days']) & \
                                    master_cgf_5b['scenario'].isin(['bep_hd_scale_up']) & \
                                    master_cgf_5b['treatment_group'].isin(['bep','none']) & \
                                    master_cgf_5b['location'].isin(['India']) & \
                                    master_cgf_5b['measure'].isin(['mean'])]
print('artifact MEAN baseline = -0.887103 29days (india)')
stunting_5b_bep_hd_universal_29

artifact MEAN baseline = -0.887103 29days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
1,stunting,mean,bep_hd_scale_up,bep,malnourished,twenty_nine_days,9.407598,-0.592402,13444.32,449.88,12994.44,-7697.927249,India
3,stunting,mean,bep_hd_scale_up,bep,normal,twenty_nine_days,9.409123,-0.590877,65971.26,2045.44,63925.82,-37772.281310,India
13,stunting,mean,bep_hd_scale_up,none,malnourished,twenty_nine_days,9.127559,-0.872441,3492.18,153.20,3338.98,-2913.061408,India
15,stunting,mean,bep_hd_scale_up,none,normal,twenty_nine_days,9.111531,-0.888469,17092.24,618.00,16474.24,-14636.848324,India

#### 2) 366 days

In [58]:
## STUNTING 366days

stunting_5b_bep_hd_universal_366 = master_cgf_5b[master_cgf_5b['risk'].isin(['stunting']) & \
                                    master_cgf_5b['timepoint'].isin(['three_six_six_days']) & \
                                    master_cgf_5b['scenario'].isin(['bep_hd_scale_up']) & \
                                    master_cgf_5b['treatment_group'].isin(['bep','none']) & \
                                    master_cgf_5b['location'].isin(['India']) & \
                                    master_cgf_5b['measure'].isin(['mean'])]
print('artifact MEAN baseline = -1.587298 366days (india)')
stunting_5b_bep_hd_universal_366

artifact MEAN baseline = -1.587298 366days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
0,stunting,mean,bep_hd_scale_up,bep,malnourished,three_six_six_days,8.755263,-1.244737,13444.32,449.88,12994.44,-16174.661623,India
2,stunting,mean,bep_hd_scale_up,bep,normal,three_six_six_days,8.756869,-1.243131,65971.26,2045.44,63925.82,-79468.188732,India
12,stunting,mean,bep_hd_scale_up,none,malnourished,three_six_six_days,8.473534,-1.526466,3492.18,153.20,3338.98,-5096.838844,India
14,stunting,mean,bep_hd_scale_up,none,normal,three_six_six_days,8.460241,-1.539759,17092.24,618.00,16474.24,-25366.363096,India

## STUNTING -BEP HOPES n' DREAMS (HD) TARGETED

#### 3) 29 days

In [61]:
## STUNTING 29days

stunting_5b_bep_hd_targeted_29 = master_cgf_5b[master_cgf_5b['risk'].isin(['stunting']) & \
                                    master_cgf_5b['timepoint'].isin(['twenty_nine_days']) & \
                                    master_cgf_5b['scenario'].isin(['bep_hd_targeted_scale_up']) & \
                                    master_cgf_5b['treatment_group'].isin(['bep','mmn','none']) & \
                                    master_cgf_5b['location'].isin(['India']) & \
                                    master_cgf_5b['measure'].isin(['mean'])]
print('artifact mean baseline= -0.887103 29days (india)')
stunting_5b_bep_hd_targeted_29

artifact mean baseline= -0.887103 29days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
17,stunting,mean,bep_hd_targeted_scale_up,bep,malnourished,twenty_nine_days,9.407598,-0.592402,13444.32,449.88,12994.44,-7697.927249,India
19,stunting,mean,bep_hd_targeted_scale_up,bep,normal,twenty_nine_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
25,stunting,mean,bep_hd_targeted_scale_up,mmn,malnourished,twenty_nine_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
27,stunting,mean,bep_hd_targeted_scale_up,mmn,normal,twenty_nine_days,9.111639,-0.888361,65971.26,2250.50,63720.76,-56607.026403,India
29,stunting,mean,bep_hd_targeted_scale_up,none,malnourished,twenty_nine_days,9.127559,-0.872441,3492.18,153.20,3338.98,-2913.061408,India
31,stunting,mean,bep_hd_targeted_scale_up,none,normal,twenty_nine_days,9.111531,-0.888469,17092.24,618.00,16474.24,-14636.848324,India

#### 4) 366 days

In [62]:
## STUNTING 366days

stunting_5b_bep_hd_targeted_366 = master_cgf_5b[master_cgf_5b['risk'].isin(['stunting']) & \
                                    master_cgf_5b['timepoint'].isin(['three_six_six_days']) & \
                                    master_cgf_5b['scenario'].isin(['bep_hd_targeted_scale_up']) & \
                                    master_cgf_5b['treatment_group'].isin(['bep','mmn','none']) & \
                                    master_cgf_5b['location'].isin(['India']) & \
                                    master_cgf_5b['measure'].isin(['mean'])]
print('artifact = -1.587298 366days (india)')
stunting_5b_bep_hd_targeted_366

artifact = -1.587298 366days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
16,stunting,mean,bep_hd_targeted_scale_up,bep,malnourished,three_six_six_days,8.755263,-1.244737,13444.32,449.88,12994.44,-16174.661623,India
18,stunting,mean,bep_hd_targeted_scale_up,bep,normal,three_six_six_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
24,stunting,mean,bep_hd_targeted_scale_up,mmn,malnourished,three_six_six_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
26,stunting,mean,bep_hd_targeted_scale_up,mmn,normal,three_six_six_days,8.460239,-1.539761,65971.26,2250.50,63720.76,-98114.759444,India
28,stunting,mean,bep_hd_targeted_scale_up,none,malnourished,three_six_six_days,8.473534,-1.526466,3492.18,153.20,3338.98,-5096.838844,India
30,stunting,mean,bep_hd_targeted_scale_up,none,normal,three_six_six_days,8.460241,-1.539759,17092.24,618.00,16474.24,-25366.363096,India

## WASTING -BEP HOPES n' DREAMS (HD) UNIVERSAL

#### 1) 29 days

In [63]:
## WASTING 29days

wasting_5b_bep_hd_universal_29 = master_cgf_5b[master_cgf_5b['risk'].isin(['wasting']) & \
                                    master_cgf_5b['timepoint'].isin(['twenty_nine_days']) & \
                                    master_cgf_5b['scenario'].isin(['bep_hd_scale_up']) & \
                                    master_cgf_5b['treatment_group'].isin(['bep','none']) & \
                                    master_cgf_5b['location'].isin(['India']) & \
                                    master_cgf_5b['measure'].isin(['mean'])]
print('artifact MEAN baseline= -0.451174 wasting 29 days (india)')
wasting_5b_bep_hd_universal_29

artifact MEAN baseline= -0.451174 wasting 29 days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
65,wasting,mean,bep_hd_scale_up,bep,malnourished,twenty_nine_days,9.869460,-0.130540,13444.32,449.88,12994.44,-1696.288927,India
67,wasting,mean,bep_hd_scale_up,bep,normal,twenty_nine_days,9.868106,-0.131894,65971.26,2045.44,63925.82,-8431.420499,India
77,wasting,mean,bep_hd_scale_up,none,malnourished,twenty_nine_days,9.578733,-0.421267,3492.18,153.20,3338.98,-1406.601271,India
79,wasting,mean,bep_hd_scale_up,none,normal,twenty_nine_days,9.573938,-0.426062,17092.24,618.00,16474.24,-7019.041131,India

#### 2) 366 days

In [65]:
## WASTING 366days

wasting_5b_bep_hd_universal_366 = master_cgf_5b[master_cgf_5b['risk'].isin(['wasting']) & \
                                    master_cgf_5b['timepoint'].isin(['three_six_six_days']) & \
                                    master_cgf_5b['scenario'].isin(['bep_hd_scale_up']) & \
                                    master_cgf_5b['treatment_group'].isin(['bep','none']) & \
                                    master_cgf_5b['location'].isin(['India']) & \
                                    master_cgf_5b['measure'].isin(['mean'])]
print('artifact MEAN baseline= -0.536096 wasting 366 days(india)')
wasting_5b_bep_hd_universal_366

artifact MEAN baseline= -0.536096 wasting 366 days(india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
64,wasting,mean,bep_hd_scale_up,bep,malnourished,three_six_six_days,9.787841,-0.212159,13444.32,449.88,12994.44,-2756.885873,India
66,wasting,mean,bep_hd_scale_up,bep,normal,three_six_six_days,9.786695,-0.213305,65971.26,2045.44,63925.82,-13635.674312,India
76,wasting,mean,bep_hd_scale_up,none,malnourished,three_six_six_days,9.499548,-0.500452,3492.18,153.20,3338.98,-1670.999802,India
78,wasting,mean,bep_hd_scale_up,none,normal,three_six_six_days,9.494744,-0.505256,17092.24,618.00,16474.24,-8323.713203,India

## WASTING -BEP HOPES n' DREAMS (HD) TARGETED

#### 3) 29 days

In [67]:
## WASTING 29days

wasting_5b_bep_hd_targeted_29 = master_cgf_5b[master_cgf_5b['risk'].isin(['wasting']) & \
                                    master_cgf_5b['timepoint'].isin(['twenty_nine_days']) & \
                                    master_cgf_5b['scenario'].isin(['bep_hd_targeted_scale_up']) & \
                                    master_cgf_5b['treatment_group'].isin(['bep','mmn','none']) & \
                                    master_cgf_5b['location'].isin(['India']) & \
                                    master_cgf_5b['measure'].isin(['mean'])]
print('artifact MEAN baseline = -0.451174 wasting 29 days (india)')
wasting_5b_bep_hd_targeted_29

artifact MEAN baseline = -0.451174 wasting 29 days (india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
81,wasting,mean,bep_hd_targeted_scale_up,bep,malnourished,twenty_nine_days,9.869460,-0.130540,13444.32,449.88,12994.44,-1696.288927,India
83,wasting,mean,bep_hd_targeted_scale_up,bep,normal,twenty_nine_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
89,wasting,mean,bep_hd_targeted_scale_up,mmn,malnourished,twenty_nine_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
91,wasting,mean,bep_hd_targeted_scale_up,mmn,normal,twenty_nine_days,9.570018,-0.429982,65971.26,2250.50,63720.76,-27398.769955,India
93,wasting,mean,bep_hd_targeted_scale_up,none,malnourished,twenty_nine_days,9.578733,-0.421267,3492.18,153.20,3338.98,-1406.601271,India
95,wasting,mean,bep_hd_targeted_scale_up,none,normal,twenty_nine_days,9.573938,-0.426062,17092.24,618.00,16474.24,-7019.041131,India

#### 4) 366 days

In [69]:
## wasting 366days

wasting_5b_bep_hd_targeted_366 = master_cgf_5b[master_cgf_5b['risk'].isin(['wasting']) & \
                                    master_cgf_5b['timepoint'].isin(['three_six_six_days']) & \
                                    master_cgf_5b['scenario'].isin(['bep_hd_targeted_scale_up']) & \
                                    master_cgf_5b['treatment_group'].isin(['bep','mmn','none']) & \
                                    master_cgf_5b['location'].isin(['India']) & \
                                    master_cgf_5b['measure'].isin(['mean'])]
print('artifact MEAN BASELINE= -0.536096 wasting 366 days(india)')
wasting_5b_bep_hd_targeted_366

artifact MEAN BASELINE= -0.536096 wasting 366 days(india)

,risk,measure,scenario,treatment_group,mother_status,timepoint,zscore,Z_SCORE,start_population,deaths,alive,alive_x_cgf,location
80,wasting,mean,bep_hd_targeted_scale_up,bep,malnourished,three_six_six_days,9.787841,-0.212159,13444.32,449.88,12994.44,-2756.885873,India
82,wasting,mean,bep_hd_targeted_scale_up,bep,normal,three_six_six_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
88,wasting,mean,bep_hd_targeted_scale_up,mmn,malnourished,three_six_six_days,0.000000,-10.000000,0.00,0.00,0.00,-0.000000,India
90,wasting,mean,bep_hd_targeted_scale_up,mmn,normal,three_six_six_days,9.491252,-0.508748,65971.26,2250.50,63720.76,-32417.787253,India
92,wasting,mean,bep_hd_targeted_scale_up,none,malnourished,three_six_six_days,9.499548,-0.500452,3492.18,153.20,3338.98,-1670.999802,India
94,wasting,mean,bep_hd_targeted_scale_up,none,normal,three_six_six_days,9.494744,-0.505256,17092.24,618.00,16474.24,-8323.713203,India

# PREVALENCE

# ================= FEB 2020 model =====================================

 I think the population needs to be updated to those alive

In [ ]:
master_stunting = pd.DataFrame()
master_wasting = pd.DataFrame()

for i in list(range(len(output_dirs))):
    cgf = pd.read_hdf(output_dirs[i] + 'category_counts.hdf').reset_index()
    cgf = (cgf.where(cgf['sex'] == 'male').dropna()
           .groupby(['input_draw','cgf_risk','risk_category','malnourishment_category']).sum()
           .reset_index())
    pop = (cgf.where(cgf['cgf_risk'] == 'stunting').dropna()
          .groupby(['input_draw','malnourishment_category'], as_index=False).sum()
          .rename(columns={'category_counts':'population'}))
    cgf = cgf.where(cgf['risk_category'] == ('cat1' or 'cat2'))
    data = cgf.merge(pop, right_on=['input_draw','malnourishment_category'], 
                     left_on=['input_draw','malnourishment_category'])
    stratified = data.groupby(['input_draw','malnourishment_category','cgf_risk']).sum().reset_index()
    overall = data.groupby(['input_draw','cgf_risk']).sum().reset_index()
    overall['malnourishment_category'] = 'all'
    data = stratified.append(overall)  
    
    stunted = (data.where(data['cgf_risk'] == 'stunting').dropna())
    stunted['percent'] = stunted['category_counts'] / stunted['population']
    stunted = (stunted.groupby(['malnourishment_category']).mean()
              .drop(columns=['input_draw','category_counts','population'])
               .reset_index()) 
    stunted['location'] = locations[i]
    master_stunting = master_stunting.append(stunted)   
    
    wasted = (data.where(data['cgf_risk'] == 'wasting').dropna())
    wasted['percent'] = wasted['category_counts'] / wasted['population']
    wasted = (wasted.groupby(['malnourishment_category']).mean()
              .drop(columns=['input_draw','category_counts','population'])
               .reset_index()) 
    wasted['location'] = locations[i]
    master_wasting = master_wasting.append(wasted)
    master_wasting

In [ ]:
master_wasting

In [ ]:
master_stunting