In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>")) #makes the display bars longer and spread out 100% across the screen width

In [2]:
from vivarium import Artifact
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from db_queries import get_ids, get_outputs
import scipy.stats

# This is runs from 2020 summer--001 and 002.1

This is the summer 2020 BEP model 001, updated from feb 2020 version with 
scenarios A,B,E and F from concept model document on github 

1) LRI birth prevalence has been added
 
2) LBWSG affects all cause mortality instead of individual causes
 
3) updated MMN effect size on birthweight: +45.16 (32.31 to 58.02; lower 0; upper 75) from +22.4g (8.3 to 36.4g)
 
4) updated BMI effect size on birthweight: -142.93g (-232.68 to -53.18) from RR = 2 (1.5-5) which translates to about-
 
  ~ birthweight from malnourished mothers = 2743.7256193373473
 
  ~ birthweight from normal mothers = 3017.6385859634224
 
  ~ birthweight difference = 273.9129666260751

 
file location: /share/costeffectiveness/results/vivarium_gates_bep/summer_001/
file location: /share/costeffectiveness/results/vivarium_gates_bep/summer_002.1/

Lexion: 

coutry order: India, Pakistan, Mali, Tanzania

BMI groups: mal and norm

In [3]:
# %cd /ihme/costeffectiveness/results/vivarium_gates_bep/summer_001/india/2020_07_29_14_35_10/count_data
# %cd /ihme/costeffectiveness/results/vivarium_gates_bep/summer_001/pakistan/2020_07_29_17_22_30/count_data
%cd /ihme/costeffectiveness/results/vivarium_gates_bep/summer_001/mali/2020_07_29_14_58_15/count_data
# %cd /ihme/costeffectiveness/results/vivarium_gates_bep/summer_001/tanzania/2020_07_29_17_25_00/count_data

%ls

/ihme/costeffectiveness/results/vivarium_gates_bep/summer_001/mali/2020_07_29_14_58_15/count_data
birth_weight.csv    deaths.csv           population.csv         ylds.csv
birth_weight.hdf    deaths.hdf           population.hdf         ylds.hdf
cgf_categories.csv  gestational_age.csv  state_person_time.csv  ylls.csv
cgf_categories.hdf  gestational_age.hdf  state_person_time.hdf  ylls.hdf
cgf_z_scores.csv    person_time.csv      transition_count.csv
cgf_z_scores.hdf    person_time.hdf      transition_count.hdf

In [4]:
#run 001 and 002.1 

output_dirs001 = ['/ihme/costeffectiveness/results/vivarium_gates_bep/summer_001/india/2020_07_29_14_35_10/count_data/',
                  '/ihme/costeffectiveness/results/vivarium_gates_bep/summer_001/pakistan/2020_07_29_17_22_30/count_data/',
                  '/ihme/costeffectiveness/results/vivarium_gates_bep/summer_001/mali/2020_07_29_14_58_15/count_data/',
                  '/ihme/costeffectiveness/results/vivarium_gates_bep/summer_001/tanzania/2020_07_29_17_25_00/count_data/']

output_dirs002 = ['/ihme/costeffectiveness/results/vivarium_gates_bep/summer_002.1/india/2020_08_21_18_23_43/count_data/',
                  '/ihme/costeffectiveness/results/vivarium_gates_bep/summer_002.1/pakistan/2020_08_22_16_37_24/count_data/',
                  '/ihme/costeffectiveness/results/vivarium_gates_bep/summer_002.1/mali/2020_08_21_18_07_24/count_data/',
                  '/ihme/costeffectiveness/results/vivarium_gates_bep/summer_002.1/tanzania/2020_08_22_17_47_06/count_data/']

#location labels
locations = ['India','Pakistan','Mali','Tanzania']

#use in sort_values to make custum sort list. I sorted by region. 
sorter = ['India','Pakistan','Mali','Tanzania']
sorterIndex = dict(zip(sorter,range(len(sorter))))


# #output_dirs = ['/ihme/costeffectiveness/results/vivarium_gates_bep/summer_001/india/2020_07_29_14_35_10/count_data/',
#                '/ihme/costeffectiveness/results/vivarium_gates_bep/summer_001/pakistan/2020_07_29_17_22_30/count_data/',
#                '/ihme/costeffectiveness/results/vivarium_gates_bep/summer_001/mali/2020_07_29_14_58_15/count_data/',
#                '/ihme/costeffectiveness/results/vivarium_gates_bep/summer_001/tanzania/2020_07_29_17_25_00/count_data/']

# ALL countries by scenario and treatment groups

In [5]:
#RUN 001 (baseline, mmn, bep_hd_scale_up and bep_hd_targeted)

master_bw_001 = pd.DataFrame()

for i in list(range(len(output_dirs001))):
    #birthweight
    bw = pd.read_hdf(output_dirs001[i] + 'birth_weight.hdf').reset_index().sort_values(by=['risk','measure','scenario','treatment_group','mother_status'])
    bw = bw.rename(columns={'value':'birthweight'})
    
    #population
    pop = pd.read_hdf(output_dirs001[i] + 'population.hdf').reset_index()
    pop = pop.where(pop['measure'] == 'total_population').dropna().rename(columns={'value':'total_population'}).drop(columns=['index','measure'])
    
    data = bw.merge(pop, right_on=['scenario','treatment_group','mother_status','input_draw'], left_on=['scenario','treatment_group','mother_status','input_draw'])
    data = data.groupby(['risk','measure','scenario','treatment_group','mother_status']).mean().drop(columns=['input_draw','index']).reset_index() #average over input draws
    data['pop_x_birthweight'] = data['birthweight'] * data['total_population']
    data['location'] = locations[i]
    master_bw_001 = master_bw_001.append(data)
    
master_bw_001.head(10)

,risk,measure,scenario,treatment_group,mother_status,birthweight,total_population,pop_x_birthweight,location
0,birth_weight,mean,baseline,bep,malnourished,0.000000,0.00,0.000000e+00,India
1,birth_weight,mean,baseline,bep,normal,0.000000,0.00,0.000000e+00,India
2,birth_weight,mean,baseline,ifa,malnourished,2764.892460,5770.46,1.595470e+07,India
3,birth_weight,mean,baseline,ifa,normal,2914.604320,28262.46,8.237389e+07,India
4,birth_weight,mean,baseline,mmn,malnourished,0.000000,0.00,0.000000e+00,India
5,birth_weight,mean,baseline,mmn,normal,0.000000,0.00,0.000000e+00,India
6,birth_weight,mean,baseline,none,malnourished,2763.734041,11166.04,3.085996e+07,India
7,birth_weight,mean,baseline,none,normal,2914.594742,54801.04,1.597228e+08,India
8,birth_weight,mean,bep_scale_up,bep,malnourished,2863.411526,13444.32,3.849662e+07,India
9,birth_weight,mean,bep_scale_up,bep,normal,2989.629098,65971.26,1.972296e+08,India

In [6]:
#RUN 002.1 (baseline, mmn, bep_hd_scale_up and bep_hd_targeted)
master_bw_002 = pd.DataFrame()

for i in list(range(len(output_dirs002))):
    #birthweight
    bw = pd.read_hdf(output_dirs002[i] + 'birth_weight.hdf').reset_index().sort_values(by=['risk','measure','scenario','treatment_group','mother_status'])
    bw = bw.rename(columns={'value':'birthweight'})
    
    #population
    pop = pd.read_hdf(output_dirs002[i] + 'population.hdf').reset_index()
    pop = pop.where(pop['measure'] == 'total_population').dropna().rename(columns={'value':'total_population'}).drop(columns=['index','measure'])
    
    data = bw.merge(pop, right_on=['scenario','treatment_group','mother_status','input_draw'], left_on=['scenario','treatment_group','mother_status','input_draw'])
    data = data.groupby(['risk','measure','scenario','treatment_group','mother_status']).mean().drop(columns=['input_draw','index']).reset_index() #average over input draws
    data['pop_x_birthweight'] = data['birthweight'] * data['total_population']
    data['location'] = locations[i]
    master_bw_002 = master_bw_002.append(data)
    
master_bw_002.head(10)

,risk,measure,scenario,treatment_group,mother_status,birthweight,total_population,pop_x_birthweight,location
0,birth_weight,mean,bep_ce_scale_up,bep,malnourished,2830.296623,13444.32,3.805141e+07,India
1,birth_weight,mean,bep_ce_scale_up,bep,normal,2955.856698,65971.26,1.950016e+08,India
2,birth_weight,mean,bep_ce_scale_up,ifa,malnourished,0.000000,0.00,0.000000e+00,India
3,birth_weight,mean,bep_ce_scale_up,ifa,normal,0.000000,0.00,0.000000e+00,India
4,birth_weight,mean,bep_ce_scale_up,mmn,malnourished,0.000000,0.00,0.000000e+00,India
5,birth_weight,mean,bep_ce_scale_up,mmn,normal,0.000000,0.00,0.000000e+00,India
6,birth_weight,mean,bep_ce_scale_up,none,malnourished,2767.109674,3492.18,9.663245e+06,India
7,birth_weight,mean,bep_ce_scale_up,none,normal,2914.488242,17092.24,4.981513e+07,India
8,birth_weight,mean,bep_ce_targeted_scale_up,bep,malnourished,2830.296623,13444.32,3.805141e+07,India
9,birth_weight,mean,bep_ce_targeted_scale_up,bep,normal,0.000000,0.00,0.000000e+00,India

In [7]:
master_bw_001['scenario'].unique()

array(['baseline', 'bep_scale_up', 'bep_targeted_scale_up',
       'mmn_scale_up'], dtype=object)

In [8]:
master_bw_001['treatment_group'].unique()

array(['bep', 'ifa', 'mmn', 'none'], dtype=object)

In [9]:
master_bw_001['measure'].unique()

array(['mean', 'proportion_below_2500g', 'sd'], dtype=object)

# ****** CHECK birthweight shift - comparison table for INDIA******


***************************************************************************************************

In [43]:
#to get the dataframe we want from run 001:

india_bw1 = master_bw_001[master_bw_001['location'].isin(['India']) & master_bw_001['measure'].isin(['mean']) & master_bw_001['scenario'].isin(['bep_targeted_scale_up']) & master_bw_001['treatment_group'].isin(['bep','mmn','none'])]
india_bw1

,risk,measure,scenario,treatment_group,mother_status,birthweight,total_population,pop_x_birthweight,location
16,birth_weight,mean,bep_targeted_scale_up,bep,malnourished,2863.411526,13444.32,3.849662e+07,India
17,birth_weight,mean,bep_targeted_scale_up,bep,normal,0.000000,0.00,0.000000e+00,India
20,birth_weight,mean,bep_targeted_scale_up,mmn,malnourished,0.000000,0.00,0.000000e+00,India
21,birth_weight,mean,bep_targeted_scale_up,mmn,normal,2959.095876,65971.26,1.952153e+08,India
22,birth_weight,mean,bep_targeted_scale_up,none,malnourished,2767.109674,3492.18,9.663245e+06,India
23,birth_weight,mean,bep_targeted_scale_up,none,normal,2914.488242,17092.24,4.981513e+07,India

In [40]:
#to get the dataframe we want from run 002.1:

india_bw2 = master_bw_002[master_bw_002['location'].isin(['India']) & master_bw_002['measure'].isin(['mean']) & master_bw_002['scenario'].isin(['bep_ce_targeted_scale_up']) & master_bw_002['treatment_group'].isin(['bep','mmn','none'])]
india_bw2

,risk,measure,scenario,treatment_group,mother_status,birthweight,total_population,pop_x_birthweight,location
8,birth_weight,mean,bep_ce_targeted_scale_up,bep,malnourished,2830.296623,13444.32,3.805141e+07,India
9,birth_weight,mean,bep_ce_targeted_scale_up,bep,normal,0.000000,0.00,0.000000e+00,India
12,birth_weight,mean,bep_ce_targeted_scale_up,mmn,malnourished,0.000000,0.00,0.000000e+00,India
13,birth_weight,mean,bep_ce_targeted_scale_up,mmn,normal,2959.095876,65971.26,1.952153e+08,India
14,birth_weight,mean,bep_ce_targeted_scale_up,none,malnourished,2767.109674,3492.18,9.663245e+06,India
15,birth_weight,mean,bep_ce_targeted_scale_up,none,normal,2914.488242,17092.24,4.981513e+07,India